### YamlMime:ManagedReference
items:
- uid: Calabonga.EntityProcessor.EntityProcessorConfiguration`1
  commentId: T:Calabonga.EntityProcessor.EntityProcessorConfiguration`1
  id: EntityProcessorConfiguration`1
  parent: Calabonga.EntityProcessor
  children:
  - Calabonga.EntityProcessor.EntityProcessorConfiguration`1.AutoFireDomainEvents
  - Calabonga.EntityProcessor.EntityProcessorConfiguration`1.EntityName
  - Calabonga.EntityProcessor.EntityProcessorConfiguration`1.SkipRuleDuplicates
  langs:
  - csharp
  - vb
  name: EntityProcessorConfiguration<TEntity>
  nameWithType: EntityProcessorConfiguration<TEntity>
  fullName: Calabonga.EntityProcessor.EntityProcessorConfiguration<TEntity>
  type: Class
  source:
    remote:
      path: src/Calabonga.EntityProcessor/EntityProcessorConfiguration.cs
      branch: main
      repo: git@github.com:Calabonga/Calabonga.EntityProcessor.git
    id: EntityProcessorConfiguration
    path: ../../src/Calabonga.EntityProcessor/EntityProcessorConfiguration.cs
    startLine: 2
  assemblies:
  - Calabonga.EntityProcessor
  namespace: Calabonga.EntityProcessor
  syntax:
    content: 'public class EntityProcessorConfiguration<TEntity> : IEntityProcessorConfiguration'
    typeParameters:
    - id: TEntity
    content.vb: >-
      Public Class EntityProcessorConfiguration(Of TEntity)
          Implements IEntityProcessorConfiguration
  inheritance:
  - System.Object
  implements:
  - Calabonga.EntityProcessor.IEntityProcessorConfiguration
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  nameWithType.vb: EntityProcessorConfiguration(Of TEntity)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Calabonga.EntityProcessor.EntityProcessorConfiguration(Of TEntity)
  name.vb: EntityProcessorConfiguration(Of TEntity)
- uid: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.SkipRuleDuplicates
  commentId: P:Calabonga.EntityProcessor.EntityProcessorConfiguration`1.SkipRuleDuplicates
  id: SkipRuleDuplicates
  parent: Calabonga.EntityProcessor.EntityProcessorConfiguration`1
  langs:
  - csharp
  - vb
  name: SkipRuleDuplicates
  nameWithType: EntityProcessorConfiguration<TEntity>.SkipRuleDuplicates
  fullName: Calabonga.EntityProcessor.EntityProcessorConfiguration<TEntity>.SkipRuleDuplicates
  type: Property
  source:
    remote:
      path: src/Calabonga.EntityProcessor/EntityProcessorConfiguration.cs
      branch: main
      repo: git@github.com:Calabonga/Calabonga.EntityProcessor.git
    id: SkipRuleDuplicates
    path: ../../src/Calabonga.EntityProcessor/EntityProcessorConfiguration.cs
    startLine: 4
  assemblies:
  - Calabonga.EntityProcessor
  namespace: Calabonga.EntityProcessor
  syntax:
    content: public bool SkipRuleDuplicates { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property SkipRuleDuplicates As Boolean
  overload: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.SkipRuleDuplicates*
  implements:
  - Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
  nameWithType.vb: EntityProcessorConfiguration(Of TEntity).SkipRuleDuplicates
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Calabonga.EntityProcessor.EntityProcessorConfiguration(Of TEntity).SkipRuleDuplicates
- uid: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.AutoFireDomainEvents
  commentId: P:Calabonga.EntityProcessor.EntityProcessorConfiguration`1.AutoFireDomainEvents
  id: AutoFireDomainEvents
  parent: Calabonga.EntityProcessor.EntityProcessorConfiguration`1
  langs:
  - csharp
  - vb
  name: AutoFireDomainEvents
  nameWithType: EntityProcessorConfiguration<TEntity>.AutoFireDomainEvents
  fullName: Calabonga.EntityProcessor.EntityProcessorConfiguration<TEntity>.AutoFireDomainEvents
  type: Property
  source:
    remote:
      path: src/Calabonga.EntityProcessor/EntityProcessorConfiguration.cs
      branch: main
      repo: git@github.com:Calabonga/Calabonga.EntityProcessor.git
    id: AutoFireDomainEvents
    path: ../../src/Calabonga.EntityProcessor/EntityProcessorConfiguration.cs
    startLine: 6
  assemblies:
  - Calabonga.EntityProcessor
  namespace: Calabonga.EntityProcessor
  syntax:
    content: public bool AutoFireDomainEvents { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property AutoFireDomainEvents As Boolean
  overload: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.AutoFireDomainEvents*
  implements:
  - Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
  nameWithType.vb: EntityProcessorConfiguration(Of TEntity).AutoFireDomainEvents
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Calabonga.EntityProcessor.EntityProcessorConfiguration(Of TEntity).AutoFireDomainEvents
- uid: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.EntityName
  commentId: P:Calabonga.EntityProcessor.EntityProcessorConfiguration`1.EntityName
  id: EntityName
  parent: Calabonga.EntityProcessor.EntityProcessorConfiguration`1
  langs:
  - csharp
  - vb
  name: EntityName
  nameWithType: EntityProcessorConfiguration<TEntity>.EntityName
  fullName: Calabonga.EntityProcessor.EntityProcessorConfiguration<TEntity>.EntityName
  type: Property
  source:
    remote:
      path: src/Calabonga.EntityProcessor/EntityProcessorConfiguration.cs
      branch: main
      repo: git@github.com:Calabonga/Calabonga.EntityProcessor.git
    id: EntityName
    path: ../../src/Calabonga.EntityProcessor/EntityProcessorConfiguration.cs
    startLine: 8
  assemblies:
  - Calabonga.EntityProcessor
  namespace: Calabonga.EntityProcessor
  syntax:
    content: public string EntityName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property EntityName As String
  overload: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.EntityName*
  implements:
  - Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
  nameWithType.vb: EntityProcessorConfiguration(Of TEntity).EntityName
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
  fullName.vb: Calabonga.EntityProcessor.EntityProcessorConfiguration(Of TEntity).EntityName
references:
- uid: Calabonga.EntityProcessor
  commentId: N:Calabonga.EntityProcessor
  name: Calabonga.EntityProcessor
  nameWithType: Calabonga.EntityProcessor
  fullName: Calabonga.EntityProcessor
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  commentId: T:Calabonga.EntityProcessor.IEntityProcessorConfiguration
  parent: Calabonga.EntityProcessor
  name: IEntityProcessorConfiguration
  nameWithType: IEntityProcessorConfiguration
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.SkipRuleDuplicates*
  commentId: Overload:Calabonga.EntityProcessor.EntityProcessorConfiguration`1.SkipRuleDuplicates
  name: SkipRuleDuplicates
  nameWithType: EntityProcessorConfiguration<TEntity>.SkipRuleDuplicates
  fullName: Calabonga.EntityProcessor.EntityProcessorConfiguration<TEntity>.SkipRuleDuplicates
  nameWithType.vb: EntityProcessorConfiguration(Of TEntity).SkipRuleDuplicates
  fullName.vb: Calabonga.EntityProcessor.EntityProcessorConfiguration(Of TEntity).SkipRuleDuplicates
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
  commentId: P:Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
  parent: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  name: SkipRuleDuplicates
  nameWithType: IEntityProcessorConfiguration.SkipRuleDuplicates
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.AutoFireDomainEvents*
  commentId: Overload:Calabonga.EntityProcessor.EntityProcessorConfiguration`1.AutoFireDomainEvents
  name: AutoFireDomainEvents
  nameWithType: EntityProcessorConfiguration<TEntity>.AutoFireDomainEvents
  fullName: Calabonga.EntityProcessor.EntityProcessorConfiguration<TEntity>.AutoFireDomainEvents
  nameWithType.vb: EntityProcessorConfiguration(Of TEntity).AutoFireDomainEvents
  fullName.vb: Calabonga.EntityProcessor.EntityProcessorConfiguration(Of TEntity).AutoFireDomainEvents
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
  commentId: P:Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
  parent: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  name: AutoFireDomainEvents
  nameWithType: IEntityProcessorConfiguration.AutoFireDomainEvents
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
- uid: Calabonga.EntityProcessor.EntityProcessorConfiguration`1.EntityName*
  commentId: Overload:Calabonga.EntityProcessor.EntityProcessorConfiguration`1.EntityName
  name: EntityName
  nameWithType: EntityProcessorConfiguration<TEntity>.EntityName
  fullName: Calabonga.EntityProcessor.EntityProcessorConfiguration<TEntity>.EntityName
  nameWithType.vb: EntityProcessorConfiguration(Of TEntity).EntityName
  fullName.vb: Calabonga.EntityProcessor.EntityProcessorConfiguration(Of TEntity).EntityName
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
  commentId: P:Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
  parent: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  name: EntityName
  nameWithType: IEntityProcessorConfiguration.EntityName
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
