### YamlMime:ManagedReference
items:
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  commentId: T:Calabonga.EntityProcessor.IEntityProcessorConfiguration
  id: IEntityProcessorConfiguration
  parent: Calabonga.EntityProcessor
  children:
  - Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
  - Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
  - Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
  langs:
  - csharp
  - vb
  name: IEntityProcessorConfiguration
  nameWithType: IEntityProcessorConfiguration
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  type: Interface
  source:
    remote:
      path: src/Calabonga.EntityProcessor/IEntityProcessorConfiguration.cs
      branch: main
      repo: git@github.com:Calabonga/Calabonga.EntityProcessor.git
    id: IEntityProcessorConfiguration
    path: ../../src/Calabonga.EntityProcessor/IEntityProcessorConfiguration.cs
    startLine: 2
  assemblies:
  - Calabonga.EntityProcessor
  namespace: Calabonga.EntityProcessor
  syntax:
    content: public interface IEntityProcessorConfiguration
    content.vb: Public Interface IEntityProcessorConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
  commentId: P:Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
  id: EntityName
  parent: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  langs:
  - csharp
  - vb
  name: EntityName
  nameWithType: IEntityProcessorConfiguration.EntityName
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
  type: Property
  source:
    remote:
      path: src/Calabonga.EntityProcessor/IEntityProcessorConfiguration.cs
      branch: main
      repo: git@github.com:Calabonga/Calabonga.EntityProcessor.git
    id: EntityName
    path: ../../src/Calabonga.EntityProcessor/IEntityProcessorConfiguration.cs
    startLine: 4
  assemblies:
  - Calabonga.EntityProcessor
  namespace: Calabonga.EntityProcessor
  syntax:
    content: string EntityName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property EntityName As String
  overload: Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
  commentId: P:Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
  id: SkipRuleDuplicates
  parent: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  langs:
  - csharp
  - vb
  name: SkipRuleDuplicates
  nameWithType: IEntityProcessorConfiguration.SkipRuleDuplicates
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
  type: Property
  source:
    remote:
      path: src/Calabonga.EntityProcessor/IEntityProcessorConfiguration.cs
      branch: main
      repo: git@github.com:Calabonga/Calabonga.EntityProcessor.git
    id: SkipRuleDuplicates
    path: ../../src/Calabonga.EntityProcessor/IEntityProcessorConfiguration.cs
    startLine: 6
  assemblies:
  - Calabonga.EntityProcessor
  namespace: Calabonga.EntityProcessor
  syntax:
    content: bool SkipRuleDuplicates { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property SkipRuleDuplicates As Boolean
  overload: Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
  commentId: P:Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
  id: AutoFireDomainEvents
  parent: Calabonga.EntityProcessor.IEntityProcessorConfiguration
  langs:
  - csharp
  - vb
  name: AutoFireDomainEvents
  nameWithType: IEntityProcessorConfiguration.AutoFireDomainEvents
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
  type: Property
  source:
    remote:
      path: src/Calabonga.EntityProcessor/IEntityProcessorConfiguration.cs
      branch: main
      repo: git@github.com:Calabonga/Calabonga.EntityProcessor.git
    id: AutoFireDomainEvents
    path: ../../src/Calabonga.EntityProcessor/IEntityProcessorConfiguration.cs
    startLine: 8
  assemblies:
  - Calabonga.EntityProcessor
  namespace: Calabonga.EntityProcessor
  syntax:
    content: bool AutoFireDomainEvents { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property AutoFireDomainEvents As Boolean
  overload: Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Calabonga.EntityProcessor
  commentId: N:Calabonga.EntityProcessor
  name: Calabonga.EntityProcessor
  nameWithType: Calabonga.EntityProcessor
  fullName: Calabonga.EntityProcessor
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName*
  commentId: Overload:Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
  name: EntityName
  nameWithType: IEntityProcessorConfiguration.EntityName
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.EntityName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates*
  commentId: Overload:Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
  name: SkipRuleDuplicates
  nameWithType: IEntityProcessorConfiguration.SkipRuleDuplicates
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.SkipRuleDuplicates
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents*
  commentId: Overload:Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
  name: AutoFireDomainEvents
  nameWithType: IEntityProcessorConfiguration.AutoFireDomainEvents
  fullName: Calabonga.EntityProcessor.IEntityProcessorConfiguration.AutoFireDomainEvents
