name: .NET Core

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore src/Calabonga.EntityProcessor.sln
      - name: Build
        run: dotnet build src/Calabonga.EntityProcessor.sln --configuration Release --no-restore
      - name: Publish Calabonga.EntityProcessor
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: src/Calabonga.EntityProcessor/Calabonga.EntityProcessor.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
